/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor. Teste
 */
package redeSocialMTP;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ifg
 */
public class CadastrarUsuario extends javax.swing.JFrame {

    Usuario u;
    File arquivo;

    /**
     * Creates new form Cadastro
     */
    public CadastrarUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_cadastro_de_usuario = new javax.swing.JLabel();
        jLabel_nome = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel_email = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel_cidade_estado = new javax.swing.JLabel();
        cidade_estado = new javax.swing.JTextField();
        jLabel_senha = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        jLabel_confirmar_senha = new javax.swing.JLabel();
        confirmar_senha = new javax.swing.JPasswordField();
        jButton_cadastrar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jButtonInserirFoto = new javax.swing.JButton();
        jLabelArquivo = new javax.swing.JLabel();
        jLabelNomeArquivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rede Social MTP");

        jLabel_cadastro_de_usuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_cadastro_de_usuario.setText("Cadastro de Usuário");

        jLabel_nome.setText("Nome:");

        jLabel_email.setText("E-mail:");

        jLabel_cidade_estado.setText("Cidade/Estado:");

        jLabel_senha.setText("Senha:");

        senha.setPreferredSize(new java.awt.Dimension(14, 23));

        jLabel_confirmar_senha.setText("Confirmar senha:");

        confirmar_senha.setPreferredSize(new java.awt.Dimension(14, 23));

        jButton_cadastrar.setText("Cadrastrar");
        jButton_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrarActionPerformed(evt);
            }
        });

        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });

        jButtonInserirFoto.setText("Inserir Foto");
        jButtonInserirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirFotoActionPerformed(evt);
            }
        });

        jLabelArquivo.setText("Arquivo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInserirFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(email))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel_cadastro_de_usuario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelArquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNomeArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_cidade_estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cidade_estado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_confirmar_senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel_cadastro_de_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidade_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cidade_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_confirmar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelArquivo))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInserirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        new TelaLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void jButton_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrarActionPerformed
        Conexao c = new Conexao();
        c.conectar();

        if (nome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo nome não pode estar vazio");
            nome.requestFocus();

        } else if (email.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo email não pode estar vazio");
            email.requestFocus();

        } else if (new String(senha.getPassword()).trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo senha não pode estar vazio");
            senha.requestFocus();

        } else {
            try {
                if (c.compararEmails(email.getText())) {
                    JOptionPane.showMessageDialog(null, "email já cadastrado");
                    email.requestFocus();
                } else {
                    if (new String(senha.getPassword()).equals(new String(confirmar_senha.getPassword()))) {
                        String senhaCript = CriptografaSenha.critografarSenha(new String(senha.getPassword()));
                        try {
                            if (arquivo != null){
                                try {
                                    c.adicionarPessoaImagem(nome.getText(), email.getText(), senhaCript, cidade_estado.getText(), arquivo);
                                } catch (FileNotFoundException ex) {
                                    JOptionPane.showMessageDialog(null, "Arquivo corrompido ou inexistente");
                                }
                                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
                                new TelaLogin().setVisible(true);
                                dispose();
                            }else if (this.u == null && arquivo == null) {
                                c.adicionarPessoa(nome.getText(), email.getText(), senhaCript, cidade_estado.getText());
                                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
                                new TelaLogin().setVisible(true);
                                dispose();
                            }
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "nao foi possivel cadastrar");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Senhas não conferem");
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "nao foi possivel cadastrar");
            }
        }

    }//GEN-LAST:event_jButton_cadastrarActionPerformed

    private void jButtonInserirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirFotoActionPerformed
        JFileChooser fc = new JFileChooser();
        int retorno = fc.showOpenDialog(this);

        if (retorno == JFileChooser.APPROVE_OPTION) {
            arquivo = fc.getSelectedFile();
            jLabelNomeArquivo.setText(arquivo.getName());
        }
    }//GEN-LAST:event_jButtonInserirFotoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cidade_estado;
    private javax.swing.JPasswordField confirmar_senha;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButtonInserirFoto;
    private javax.swing.JButton jButton_cadastrar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JLabel jLabelArquivo;
    private javax.swing.JLabel jLabelNomeArquivo;
    private javax.swing.JLabel jLabel_cadastro_de_usuario;
    private javax.swing.JLabel jLabel_cidade_estado;
    private javax.swing.JLabel jLabel_confirmar_senha;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_senha;
    private javax.swing.JTextField nome;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables
}
