/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redeSocialMTP;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ifg
 */
public class TelaCriacaoDePost extends javax.swing.JFrame {
 
    Usuario u;        
    File arquivo = null;
    
    /**
     * Creates new form TelaCriaçaoDePost
     */
    public TelaCriacaoDePost(Usuario user) {
        this.u = user;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        abrirImagem = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setText("Post");

        abrirImagem.setText("Abrir Imagem");
        abrirImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirImagemActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvar)
                        .addGap(18, 18, 18)
                        .addComponent(abrirImagem)
                        .addGap(18, 18, 18)
                        .addComponent(cancelar)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar)
                    .addComponent(abrirImagem)
                    .addComponent(cancelar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal(this.u).setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        if(jTextPane1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Campo post  não pode estar vazio");
            jTextPane1.requestFocus();
        }
       else if(jTextPane1.getText().length() > 140){
            JOptionPane.showMessageDialog(null, "Texto nao pode ultrapassar  140 caracteres");
            jTextPane1.requestFocus();
        }
       else if(arquivo != null) {
           Conexao c = new Conexao();
            c.conectar();
            try {
                c.inserirPostImagem(jTextPane1.getText(), u.getId(), arquivo);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TelaCriacaoDePost.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "post salvo com sucesso! ");
            new TelaPrincipal(this.u).setVisible(true);
            dispose();
           
       }
        else{
            Conexao c = new Conexao();
            c.conectar();
            c.inserir_post(jTextPane1.getText(), u.getId());
            JOptionPane.showMessageDialog(null, "post salvo com sucesso! ");
            new TelaPrincipal(this.u).setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_salvarActionPerformed

    private void abrirImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirImagemActionPerformed
        // TODO add your handling code here:
        byte[] imagem;
        
        JFileChooser fc = new JFileChooser();
        int retorno = fc.showOpenDialog(this);
			
            if (retorno == JFileChooser.APPROVE_OPTION) {
                    arquivo = fc.getSelectedFile();
                    jLabel2.setText(arquivo.getName());
            }	
    }//GEN-LAST:event_abrirImagemActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirImagem;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables
}
