/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redeSocialMTP;

import java.util.Date;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author ifg
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Usuario u;
    Post post;

    /**
     * Creates new form TelaInicial
     */
    public TelaPrincipal() {
        initComponents();

    }

    public TelaPrincipal(Usuario user) {
        initComponents();
        this.u = user;
        jLabel_usuario.setText(String.format("%s", user.getNome()));
        setLocationRelativeTo (null);
        mostrar_post();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_foto = new javax.swing.JScrollPane();
        jButton_alterar_cadastro = new javax.swing.JButton();
        jLabel_buscar_perfil = new javax.swing.JLabel();
        jLabel_ola = new javax.swing.JLabel();
        jLabel_usuario = new javax.swing.JLabel();
        jTextField_buscar_usurio = new javax.swing.JTextField();
        jButton_criar_post = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelUsuario1 = new javax.swing.JLabel();
        jLabelData1 = new javax.swing.JLabel();
        jLabelLike1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabelUsuario2 = new javax.swing.JLabel();
        jLabelData2 = new javax.swing.JLabel();
        jLabelLike2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabelLike3 = new javax.swing.JLabel();
        jLabelData3 = new javax.swing.JLabel();
        jLabelUsuario3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_alterar_cadastro.setText("Alterar Cadastro");
        jButton_alterar_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterar_cadastroActionPerformed(evt);
            }
        });

        jLabel_buscar_perfil.setText("buscar perfil");

        jLabel_ola.setText("Olá,");

        jLabel_usuario.setText("usuario");

        jTextField_buscar_usurio.setText("buscar");

        jButton_criar_post.setText("Criar Post");
        jButton_criar_post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_criar_postActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabelUsuario1.setText("Usuario");

        jLabelData1.setText("data");

        jLabelLike1.setText("like");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jLabelUsuario2.setText("Usuario");

        jLabelData2.setText("data");

        jLabelLike2.setText("like");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        jLabelLike3.setText("like");

        jLabelData3.setText("data");

        jLabelUsuario3.setText("Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_alterar_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel_ola)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel_usuario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_buscar_usurio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_buscar_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelUsuario2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelData2)
                                    .addGap(102, 102, 102)
                                    .addComponent(jLabelLike2))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelUsuario1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelData1)
                                        .addComponent(jButton_criar_post))
                                    .addGap(102, 102, 102)
                                    .addComponent(jLabelLike1))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelUsuario3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelData3)
                                    .addGap(102, 102, 102)
                                    .addComponent(jLabelLike3))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_alterar_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_buscar_perfil))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_ola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_usuario)))
                            .addComponent(jScrollPane_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jTextField_buscar_usurio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_criar_post)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario1)
                    .addComponent(jLabelData1)
                    .addComponent(jLabelLike1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario2)
                    .addComponent(jLabelData2)
                    .addComponent(jLabelLike2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario3)
                    .addComponent(jLabelData3)
                    .addComponent(jLabelLike3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_alterar_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterar_cadastroActionPerformed
        new AlterarUsuario(this.u).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_alterar_cadastroActionPerformed

    private void jButton_criar_postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_criar_postActionPerformed
        new TelaCriacaoDePost(this.u).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_criar_postActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_alterar_cadastro;
    private javax.swing.JButton jButton_criar_post;
    private javax.swing.JLabel jLabelData1;
    private javax.swing.JLabel jLabelData2;
    private javax.swing.JLabel jLabelData3;
    private javax.swing.JLabel jLabelLike1;
    private javax.swing.JLabel jLabelLike2;
    private javax.swing.JLabel jLabelLike3;
    private javax.swing.JLabel jLabelUsuario1;
    private javax.swing.JLabel jLabelUsuario2;
    private javax.swing.JLabel jLabelUsuario3;
    private javax.swing.JLabel jLabel_buscar_perfil;
    private javax.swing.JLabel jLabel_ola;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane_foto;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField_buscar_usurio;
    // End of variables declaration//GEN-END:variables

    private Object Cadastro() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void SetLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void mostrar_post() {
        SimpleDateFormat dataFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        ArrayList<Post> posts = new ArrayList();
        
        Conexao c = new Conexao();
        c.conectar();
        posts =  c.buscarPost();
        
        if(!posts.equals(null)){
            Collections.reverse(posts);
            
            if(posts.size() == 1){
                jLabelUsuario1.setText(String.format("%s",c.buscarUsuarioDoPost(posts.get(0).getId())));
                jLabelData1.setText(dataFormat.format(posts.get(0).getDataPost()));
                jTextArea1.setText(String.format("%s",posts.get(0).getTexto()));

            }else if (posts.size() == 2){
                jLabelUsuario1.setText(String.format("%s",c.buscarUsuarioDoPost(posts.get(0).getId())));
                jLabelData1.setText(dataFormat.format(posts.get(0).getDataPost()));
                jTextArea1.setText(String.format("%s",posts.get(0).getTexto()));
                
                jLabelUsuario2.setText(String.format("%s",c.buscarUsuarioDoPost(posts.get(1).getId())));
                jLabelData2.setText(dataFormat.format(posts.get(1).getDataPost()));
                jTextArea2.setText(String.format("%s",posts.get(1).getTexto()));

            }else if (posts.size() > 2){

                jLabelUsuario1.setText(String.format("%s",c.buscarUsuarioDoPost(posts.get(0).getId())));
                jLabelData1.setText(dataFormat.format(posts.get(0).getDataPost()));
                jTextArea1.setText(String.format("%s",posts.get(0).getTexto()));

                jLabelUsuario2.setText(String.format("%s",c.buscarUsuarioDoPost(posts.get(1).getId())));
                jLabelData2.setText(dataFormat.format(posts.get(1).getDataPost()));
                jTextArea2.setText(String.format("%s",posts.get(1).getTexto()));

                jLabelUsuario3.setText(String.format("%s",c.buscarUsuarioDoPost(posts.get(2).getId())));
                jLabelData3.setText(dataFormat.format(posts.get(2).getDataPost()));
                jTextArea3.setText(String.format("%s",posts.get(2).getTexto()));
            }
        }else{
            JOptionPane.showMessageDialog(null, "Não existe post");
        }

    }
}
